# Generated by Django 5.0.6 on 2024-06-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='task',
        ),
    ]
